import maya.cmds as cmds

#with open(r'f:\example.txt', 'wt') as f:
#    f.write('hello world')

def export_obj(obj):
    vert_count = cmds.polyEvaluate(obj, v=True)
    face_count = cmds.polyEvaluate(obj, f=True)
    
    #print('vertices', vert_count, 'faces', face_count)
    with open(r'f:\{}.obj'.format(obj), 'wt') as fs:
        fs.write('# file generated by our exporter\n\n')
        
        for v in range(vert_count):
            pos = cmds.xform( "{}.vtx[{}]".format(obj, v), q=True, ws=True, t=True)
            fs.write('v {} {} {}\n'.format(pos[0], pos[1], pos[2]))
            
        faces = cmds.polyInfo(obj, fv=True)
        for face in faces:
            indices = face.split()[2:]
            fs.write('f ')
            for indice in indices:
                fs.write('{} '.format(int(indice)+1))
            fs.write('\n')
    
    
export_obj(cmds.ls(sl=True)[0])
